version: "3.9"
services:
  node-task-manager:
    container_name: node-task-manager
    image: node-task-manager
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.docker
    environment:
      - MONGO_HOST=$MONGO_HOST
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB_NAME=$MONGO_DB_NAME
      - WAIT_HOSTS=mongo:27017
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: node-task-manager-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mongodata: